Added array sum and array product.
TheAlgorithms/Solidity pull request #10
Opened 2022-06-19 12:24 UTC by fps8k

## Array addition and multiplication.

## Environment

- Compiler version: 0.8.7
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Remix

- Operating system: Windows

## I added a contract that shows how array addition and multiplication are done.

2022-06-19 17:22 UTC, Panquesito7 requested changes

2022-06-19 17:22 UTC, Panquesito7 commented on Maths/Array functions/AddArray.sol
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-06-19 17:22 UTC, Panquesito7 commented on Maths/Array functions/MulArray.sol
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-06-20 12:01 UTC, mkubdev approved these changes
Hey, look good to me 👍🏻

2022-06-20 18:54 UTC, fps8k commented
> Hey, look good to me 👍🏻

I am glad it does look good to you 😊.

2022-06-21 06:28 UTC, merged