Selection Sort
TheAlgorithms/Solidity pull request #27
Opened 2022-09-20 16:34 UTC by Chiadikaobixo

Selection sort is a sorting algorithm, whereby you place the smaller values into sorted position one at a time.
https://en.wikipedia.org/wiki/Selection_sort

2022-09-20 17:31 UTC, Panquesito7 commented on src/Sorts/SelectionSort.sol
> + * @author Chiadikaobi https://github.com/Chiadikaobixo
We should also use this syntax in another PR. Will be making an issue for it soon. 🙂
```suggestion
 * @author [Chiadikaobi](https://github.com/Chiadikaobixo)
```

2022-09-26 06:36 UTC, Chiadikaobixo commented
Hi @mkubdev kindly look into this.

2022-09-26 08:23 UTC, mkubdev requested changes
Hi! Thanks for your contribution ✨
The sort algorithm looks good to me, there is space for optimization also.

Do you know about [Foundry](https://book.getfoundry.sh/getting-started/first-steps)? We encourage folks to write the Foundry test alongside the PR. You can see one example [here](https://github.com/TheAlgorithms/Solidity/blob/main/src/Sorts/test/BubbleSort.t.sol)

Have a good day!

2022-09-26 08:23 UTC, mkubdev commented on src/Sorts/SelectionSort.sol
> +contract SelectionSort{
```suggestion
contract SelectionSort {
```

2022-09-26 08:33 UTC, Chiadikaobixo commented
I will definately look into it. must i write test for this selection sort before it will be merged?

2022-09-26 09:22 UTC, mkubdev commented
> I will definately look into it. must i write test for this selection sort before it will be merged?

We can merge it, and open an issue to add the test later. :)

2022-09-26 09:27 UTC, mkubdev approved these changes
LGTM 🚀

2022-09-26 09:27 UTC, merged