Changes to use markdown formating. issue #2
TheAlgorithms/Solidity pull request #48
Opened 2022-10-18 12:36 UTC by priyda

changes to fix issue #28

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/Solidity/pull/48"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-10-18 15:27 UTC, Panquesito7 requested changes
You might want to do the same for all the other files you modified. 🙂

2022-10-18 15:27 UTC, Panquesito7 commented on src/Maths/AddArray.sol
> + * @author Anthony (fps)  (https://github.com/fps8k)
```suggestion
 * @author [Anthony (fps)](https://github.com/fps8k)
```

2022-10-18 15:27 UTC, Panquesito7 commented on src/Maths/AliquotSum.sol
> + * @author Perelyn (https://github.com/Perelyn-sama)
```suggestion
 * @author [Perelyn](https://github.com/Perelyn-sama)
```

2022-10-18 15:27 UTC, Panquesito7 commented on src/Maths/Area.sol
> + * @author Perelyn (https://github.com/Perelyn-sama)
```suggestion
 * @author [Perelyn](https://github.com/Perelyn-sama)
```

2022-10-18 15:27 UTC, Panquesito7 commented on src/Maths/AverageMean.sol
> + * @author Perelyn (https://github.com/Perelyn-sama)
```suggestion
 * @author [Perelyn](https://github.com/Perelyn-sama)
```

2022-10-18 15:27 UTC, Panquesito7 commented on src/Maths/MulArray.sol
> + * @author Anthony (fps)  (https://github.com/fps8k)
```suggestion
 * @author [Anthony (fps)](https://github.com/fps8k)
```

2022-10-18 15:27 UTC, Panquesito7 commented on src/Maths/Percentage.sol
> + * @author Anthony (fps)  (https://github.com/fps8k)
```suggestion
 * @author [Anthony (fps)](https://github.com/fps8k)
```

2022-10-18 15:27 UTC, Panquesito7 commented on src/Maths/armstrongNumber.sol
> + * @author Wenceslas Sanchez (https://github.com/wenceslas-sanchez)
```suggestion
 * @author [Wenceslas Sanchez](https://github.com/wenceslas-sanchez)
```

2022-10-18 15:27 UTC, Panquesito7 commented on src/Maths/factorial.sol
> + * @author Wenceslas Sanchez (https://github.com/wenceslas-sanchez)
```suggestion
 * @author [Wenceslas Sanchez](https://github.com/wenceslas-sanchez)
```

2022-10-19 03:40 UTC, priyda commented
> You might want to do the same for all the other files you modified. 🙂

On files I modified were not merged into main branch so didn't modify them. should I make another pull request?

2022-10-19 14:51 UTC, mkubdev commented
Hi @Panquesito7, can we commit our suggestion?

2022-10-20 02:55 UTC, Panquesito7 commented
> > You might want to do the same for all the other files you modified. 🙂
> 
> On files I modified were not merged into main branch so didn't modify them. should I make another pull request?

Hmm, what do you mean exactly? 🤔

2022-10-21 22:19 UTC, priyda commented
> > > You might want to do the same for all the other files you modified. 🙂
> > 
> > 
> > On files I modified were not merged into main branch so didn't modify them. should I make another pull request?
> 
> Hmm, what do you mean exactly? 🤔

please ignore, I made you confused  :) , I will commit suggestions , thank you :)

2022-10-23 00:25 UTC, Panquesito7 approved these changes
Thanks! 🚀

2022-10-23 00:30 UTC, merged