Common SPDX License
TheAlgorithms/Solidity pull request #76
Opened 2022-10-31 16:55 UTC by sreekar9601

Using ``// SPDX-License-Identifier: MIT`` as license identifier across all contracts

2022-11-01 20:53 UTC, Panquesito7 approved these changes
Thanks! 🚀

2022-11-01 20:54 UTC, Panquesito7 requested changes
Please resolve the merge conflicts [**here**](https://github.com/TheAlgorithms/Solidity/pull/76/conflicts). If you need any help you need, let us know. 🙂

2022-11-02 09:21 UTC, mkubdev approved these changes
LGTM, fixed the conflict. (Don't forget to sync before pushing changes) 🦀

2022-11-02 12:38 UTC, shuklaritvik06 approved these changes

2022-11-02 16:30 UTC, merged